"""create core tables

Revision ID: 7d04311b0d5e
Revises:
Create Date: 2026-09-14 21:17:51.055107
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7d04311b0d5e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "STUDENT",
                "MENTOR",
                "COORDINATOR",
                name="user_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "interview_slots",
        sa.Column("mentor_id", sa.Uuid(), nullable=False),
        sa.Column("topic", sa.String(length=200), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "ADVANCED",
                name="slot_difficulty",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE",
                "BOOKED",
                "COMPLETED",
                "CANCELLED",
                name="slot_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("ends_at > starts_at", name="slot_positive_duration"),
        sa.ForeignKeyConstraint(
            ["mentor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_slots_mentor_id"), "interview_slots", ["mentor_id"], unique=False
    )
    op.create_index(
        op.f("ix_interview_slots_starts_at"), "interview_slots", ["starts_at"], unique=False
    )
    op.create_table(
        "bookings",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("slot_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CONFIRMED",
                "CANCELLED",
                "COMPLETED",
                "NO_SHOW",
                name="booking_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["interview_slots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bookings_slot_id"), "bookings", ["slot_id"], unique=False)
    op.create_index(op.f("ix_bookings_student_id"), "bookings", ["student_id"], unique=False)
    op.create_table(
        "feedback",
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("mentor_id", sa.Uuid(), nullable=False),
        sa.Column("strengths", sa.Text(), nullable=False),
        sa.Column("improvements", sa.Text(), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mentor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("booking_id"),
    )
    op.create_index(op.f("ix_feedback_mentor_id"), "feedback", ["mentor_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feedback_mentor_id"), table_name="feedback")
    op.drop_table("feedback")
    op.drop_index(op.f("ix_bookings_student_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_slot_id"), table_name="bookings")
    op.drop_table("bookings")
    op.drop_index(op.f("ix_interview_slots_starts_at"), table_name="interview_slots")
    op.drop_index(op.f("ix_interview_slots_mentor_id"), table_name="interview_slots")
    op.drop_table("interview_slots")
    op.drop_table("users")
    # ### end Alembic commands ###
